export interface Theme {
  id: string
  name: string
  description: string
  colors: {
    light: Record<string, string>
    dark: Record<string, string>
  }
}

export const themes: Theme[] = [
  {
    id: "amber-glow",
    name: "Amber Glow",
    description: "Warm and professional with amber accents",
    colors: {
      light: {
        "--card": "#ffffff",
        "--ring": "#f59e0b",
        "--input": "#e5e7eb",
        "--muted": "#f9fafb",
        "--accent": "#fffbeb",
        "--border": "#e5e7eb",
        "--radius": "0.375rem",
        "--chart-1": "#f59e0b",
        "--chart-2": "#d97706",
        "--chart-3": "#b45309",
        "--chart-4": "#92400e",
        "--chart-5": "#78350f",
        "--popover": "#ffffff",
        "--primary": "#f59e0b",
        "--sidebar": "#f9fafb",
        "--spacing": "0.25rem",
        "--font-mono": "JetBrains Mono, monospace",
        "--font-sans": "Inter, sans-serif",
        "--secondary": "#f3f4f6",
        "--background": "#ffffff",
        "--font-serif": "Source Serif 4, serif",
        "--foreground": "#262626",
        "--destructive": "#ef4444",
        "--shadow-blur": "8px",
        "--shadow-color": "hsl(0 0% 0%)",
        "--sidebar-ring": "#f59e0b",
        "--shadow-spread": "-1px",
        "--letter-spacing": "0em",
        "--shadow-opacity": "0.1",
        "--sidebar-accent": "#fffbeb",
        "--sidebar-border": "#e5e7eb",
        "--card-foreground": "#262626",
        "--shadow-offset-x": "0px",
        "--shadow-offset-y": "4px",
        "--sidebar-primary": "#f59e0b",
        "--muted-foreground": "#6b7280",
        "--accent-foreground": "#92400e",
        "--popover-foreground": "#262626",
        "--primary-foreground": "#000000",
        "--sidebar-foreground": "#262626",
        "--secondary-foreground": "#4b5563",
        "--destructive-foreground": "#ffffff",
        "--sidebar-accent-foreground": "#92400e",
        "--sidebar-primary-foreground": "#ffffff",
      },
      dark: {
        "--card": "#262626",
        "--ring": "#f59e0b",
        "--input": "#404040",
        "--muted": "#262626",
        "--accent": "#92400e",
        "--border": "#404040",
        "--chart-1": "#fbbf24",
        "--chart-2": "#d97706",
        "--chart-3": "#92400e",
        "--chart-4": "#b45309",
        "--chart-5": "#92400e",
        "--popover": "#262626",
        "--primary": "#f59e0b",
        "--sidebar": "#0f0f0f",
        "--secondary": "#262626",
        "--background": "#171717",
        "--foreground": "#e5e5e5",
        "--destructive": "#ef4444",
        "--sidebar-ring": "#f59e0b",
        "--sidebar-accent": "#92400e",
        "--sidebar-border": "#404040",
        "--card-foreground": "#e5e5e5",
        "--sidebar-primary": "#f59e0b",
        "--muted-foreground": "#a3a3a3",
        "--accent-foreground": "#fde68a",
        "--popover-foreground": "#e5e5e5",
        "--primary-foreground": "#000000",
        "--sidebar-foreground": "#e5e5e5",
        "--secondary-foreground": "#e5e5e5",
        "--destructive-foreground": "#ffffff",
        "--sidebar-accent-foreground": "#fde68a",
        "--sidebar-primary-foreground": "#ffffff",
      },
    },
  },
  {
    id: "bubblegum",
    name: "Bubblegum",
    description: "Playful and vibrant with pink tones",
    colors: {
      light: {
        "--card": "#fdedc9",
        "--ring": "#e670ab",
        "--input": "#e4e4e4",
        "--muted": "#b2e1eb",
        "--accent": "#fbe2a7",
        "--border": "#d04f99",
        "--radius": "0.4rem",
        "--chart-1": "#e670ab",
        "--chart-2": "#84d2e2",
        "--chart-3": "#fbe2a7",
        "--chart-4": "#f3a0ca",
        "--chart-5": "#d7488e",
        "--popover": "#ffffff",
        "--primary": "#d04f99",
        "--sidebar": "#f8d8ea",
        "--font-mono": "Fira Code, monospace",
        "--font-sans": "Poppins, sans-serif",
        "--secondary": "#8acfd1",
        "--background": "#f6e6ee",
        "--font-serif": "Lora, serif",
        "--foreground": "#5b5b5b",
        "--destructive": "#f96f70",
        "--shadow-blur": "0px",
        "--shadow-color": "hsl(325.78 58.18% 56.86% / 0.5)",
        "--sidebar-ring": "#ec4899",
        "--shadow-spread": "0px",
        "--shadow-opacity": "1.0",
        "--sidebar-accent": "#f9a8d4",
        "--sidebar-border": "#f3e8ff",
        "--card-foreground": "#5b5b5b",
        "--shadow-offset-x": "3px",
        "--shadow-offset-y": "3px",
        "--sidebar-primary": "#ec4899",
        "--muted-foreground": "#7a7a7a",
        "--accent-foreground": "#333333",
        "--popover-foreground": "#5b5b5b",
        "--primary-foreground": "#ffffff",
        "--sidebar-foreground": "#333333",
        "--secondary-foreground": "#333333",
        "--destructive-foreground": "#ffffff",
        "--sidebar-accent-foreground": "#333333",
        "--sidebar-primary-foreground": "#ffffff",
      },
      dark: {
        "--card": "#1c2e38",
        "--ring": "#50afb6",
        "--input": "#20333d",
        "--muted": "#24272b",
        "--accent": "#c67b96",
        "--border": "#324859",
        "--chart-1": "#50afb6",
        "--chart-2": "#e4a2b1",
        "--chart-3": "#c67b96",
        "--chart-4": "#175c6c",
        "--chart-5": "#24272b",
        "--popover": "#1c2e38",
        "--primary": "#fbe2a7",
        "--sidebar": "#101f28",
        "--font-mono": "Fira Code, monospace",
        "--font-sans": "Poppins, sans-serif",
        "--secondary": "#e4a2b1",
        "--background": "#12242e",
        "--font-serif": "Lora, serif",
        "--foreground": "#f3e3ea",
        "--destructive": "#e35ea4",
        "--shadow-color": "#324859",
        "--sidebar-ring": "#ec4899",
        "--sidebar-accent": "#f9a8d4",
        "--sidebar-border": "#374151",
        "--card-foreground": "#f3e3ea",
        "--sidebar-primary": "#ec4899",
        "--muted-foreground": "#e4a2b1",
        "--accent-foreground": "#f3e3ea",
        "--popover-foreground": "#f3e3ea",
        "--primary-foreground": "#12242e",
        "--sidebar-foreground": "#f3f4f6",
        "--secondary-foreground": "#12242e",
        "--destructive-foreground": "#12242e",
        "--sidebar-accent-foreground": "#1f2937",
        "--sidebar-primary-foreground": "#ffffff",
      },
    },
  },
  {
    id: "hazel",
    name: "Hazel",
    description: "Elegant and sophisticated with purple hues",
    colors: {
      light: {
        "--card": "#ffffff",
        "--ring": "#8a79ab",
        "--input": "#eae7f0",
        "--muted": "#dcd9e3",
        "--accent": "#e6a5b8",
        "--border": "#cec9d9",
        "--radius": "0.5rem",
        "--chart-1": "#8a79ab",
        "--chart-2": "#e6a5b8",
        "--chart-3": "#77b8a1",
        "--chart-4": "#f0c88d",
        "--chart-5": "#a0bbe3",
        "--popover": "#ffffff",
        "--primary": "#8a79ab",
        "--sidebar": "#f1eff5",
        "--spacing": "0.25rem",
        "--font-mono": "Fira Code, Courier New, monospace",
        "--font-sans": "Geist, sans-serif",
        "--secondary": "#dfd9ec",
        "--background": "#f8f7fa",
        "--font-serif": "Lora, Georgia, serif",
        "--foreground": "#3d3c4f",
        "--destructive": "#d95c5c",
        "--shadow-blur": "5px",
        "--shadow-color": "hsl(0 0% 0%)",
        "--sidebar-ring": "#8a79ab",
        "--shadow-spread": "1px",
        "--letter-spacing": "0em",
        "--shadow-opacity": "0.06",
        "--sidebar-accent": "#e6a5b8",
        "--sidebar-border": "#d7d2e0",
        "--card-foreground": "#3d3c4f",
        "--shadow-offset-x": "1px",
        "--shadow-offset-y": "2px",
        "--sidebar-primary": "#8a79ab",
        "--muted-foreground": "#6b6880",
        "--accent-foreground": "#4b2e36",
        "--popover-foreground": "#3d3c4f",
        "--primary-foreground": "#f8f7fa",
        "--sidebar-foreground": "#3d3c4f",
        "--secondary-foreground": "#3d3c4f",
        "--destructive-foreground": "#f8f7fa",
        "--sidebar-accent-foreground": "#4b2e36",
        "--sidebar-primary-foreground": "#f8f7fa",
      },
      dark: {
        "--card": "#232030",
        "--ring": "#a995c9",
        "--input": "#2a273a",
        "--muted": "#242031",
        "--accent": "#372e3f",
        "--border": "#302c40",
        "--chart-1": "#a995c9",
        "--chart-2": "#f2b8c6",
        "--chart-3": "#77b8a1",
        "--chart-4": "#f0c88d",
        "--chart-5": "#a0bbe3",
        "--popover": "#232030",
        "--primary": "#a995c9",
        "--sidebar": "#16141e",
        "--secondary": "#5a5370",
        "--background": "#1a1823",
        "--foreground": "#e0ddef",
        "--destructive": "#e57373",
        "--sidebar-ring": "#a995c9",
        "--sidebar-accent": "#372e3f",
        "--sidebar-border": "#2a273a",
        "--card-foreground": "#e0ddef",
        "--sidebar-primary": "#a995c9",
        "--muted-foreground": "#a09aad",
        "--accent-foreground": "#f2b8c6",
        "--popover-foreground": "#e0ddef",
        "--primary-foreground": "#1a1823",
        "--sidebar-foreground": "#e0ddef",
        "--secondary-foreground": "#e0ddef",
        "--destructive-foreground": "#1a1823",
        "--sidebar-accent-foreground": "#f2b8c6",
        "--sidebar-primary-foreground": "#1a1823",
      },
    },
  },
]

export function getThemeById(id: string): Theme | undefined {
  return themes.find((theme) => theme.id === id)
}
